COMBO_FAMILIAR = '//*[@id="3"]/div[3]/div/button'
BOTON_ARMA_TU_PIZZA = '//*[@id="pizza-creation-content"]/div[1]/div[2]/div[1]'
SUPER_PEPPERONI = '//*[@id="pizza-creation-content"]/div[1]/div[2]/div[1]/ul/li[3]'
MASA_DELGADA = '//*[@id="pizza-creation-content"]/div[2]/div[1]/div[2]/div[2]/button[2]'
BOTON_SIGUIENTE = '/html/body/div[10]/div/div/div/div/div/div[4]/button'  #SE USA LUEGO DE ARMAR LA PIZZA
PALITOS_DE_AJO = '//*[@id="pizza-creation-content"]/div/div/button[4]'   #SE ELIGE COMO SIDE DEL COMBO
COCA_ZERO = '//*[@id="pizza-creation-content"]/div/div/button[3]'
INPUT_DIRECCION = '/html/body/div[4]/div/div/div/div[1]/div/div[1]/div[1]/div[1]/input'   #SE COLOCA AL FINAL DEL PEDIDO
SELECCIONAR_DIRECCION = '/html/body/div[4]/div/div/div/div[1]/div/div[1]/div[2]/button[2]' #BOTON PARA ASIGNAR DIRECCION
NUMERO_DEPTO = '//*[@id="apartmentDetails"]'   #PUEDE SER DE CASA TAMBIEN, DA LO MISMO
BOTON_CONFIRMAR = '/html/body/div[4]/div/div/div/div[2]/div/form/div[2]/button'
CONTINUAR_PAGO = '/html/body/div[1]/div/div[2]/nav/button'
INPUT_NOMBRE = '//*[@id="name"]'
INPUT_MAIL = '//*[@id="email"]'
INPUT_TELEFONO = '//*[@id="phone"]'
WEB_PAY = '//*[@id="ga-container-payment-methods"]/div[2]/div/button[2]'
CONFIRMACION_FINAL = '//*[@id="ga-btn-checkout-confirm-order"]'
TARJETA_DEBITO = '/html/body/app-root/app-home/main/app-home-normal/main/div/div/div/app-payment/a[3]'
SELECCION_BANCO = '//*[@id="no-show-second"]/button'
SANTANDER = '//*[@id="no-show-second"]/ul/li[2]/a'
INPUT_TARJETA = '/html/body/app-root/app-home/main/app-home-normal/main/div/div/div/app-debit/div/form/div[2]/input'
INPUT_4D = '//*[@id="contenedor"]/center/table[3]/tbody/tr/td[2]/input'
BOTON_CONTINUAR_FINAL = '/html/body/app-root/app-home/main/app-home-normal/main/div/div/div/app-debit/div/form/button'
BOTON_ACEPTAR_FINAL = '//*[@id="cubrex"]'
C1 = '/html/body/center/table[3]/tbody/tr[1]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td[2]/table/tbody/tr[1]/td'
C2 = '/html/body/center/table[3]/tbody/tr[1]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td[4]/table/tbody/tr[1]/td'
C3 = '/html/body/center/table[3]/tbody/tr[1]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td[6]/table/tbody/tr[1]/td'
INPUT_C1 = '/html/body/center/table[3]/tbody/tr[1]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td[2]/table/tbody/tr[2]/td/input'
INPUT_C2 = '/html/body/center/table[3]/tbody/tr[1]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td[4]/table/tbody/tr[2]/td/input'
INPUT_C3 = '/html/body/center/table[3]/tbody/tr[1]/td/table/tbody/tr[2]/td[2]/table/tbody/tr/td[6]/table/tbody/tr[2]/td/input'
TERMINAR_PEDIDO = '//*[@id="botones"]/input[1]'